---

- name: Install python-pycurl
  yum: name=python-pycurl state=installed

- name: Import jenkins key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
